### ISSUE TITLE
Add BMC Client Management

### ISSUE THREAD

**Issue by Underdoge** [NCSC-NL/log4shell#100]
[Vendor's write-up](https://bmcsites.force.com/casemgmt/sc_KnowledgeArticle?sfdcid=kA33n0000000ERUCA2&type=FAQ)

**Comment by FF9680E59F9B** [comment]
I've added the products listed on https://community.bmc.com/s/news/aA33n000000TSUdCAO/bmc-security-advisory-for-cve202144228-log4shell-vulnerability. This includes BMC Client Management. Commit: 877bb2faf49ab00bf893814f7fad128a60bb5423
