### ISSUE TITLE
Correction of the name of Check Point Software Technologies

### ISSUE THREAD

**Issue by mybasementcloud** [NCSC-NL/log4shell#102]
Hello,
Thanks for this comprehensive list,

Please correct the entries for Check Point Software Technologies, currently listed as Checkpoint, which is a different company, as either Check Point or Check Point Software Technologies.
This will make it easier for actual Check Point customers to easily check your information.

Thanks
Eric
aka ericb(at)checkpoint(dot)com

**Comment by FF9680E59F9B** [comment]
I see that his has already been corrected. Thanks for bringing this to our attention.
