### ISSUE TITLE
Please remove Chef Infra Server from the list

### ISSUE THREAD

**Issue by tas50** [NCSC-NL/log4shell#114]
Chef Infra Server is in this list due to an issue I opened to track the log4j issue. We depend on Elasticsearch and at the time Elastic had not determined if ES was vulnerable or not. They have since published a statement that Elasticsearch is not vulnerable. Chef Infra Server is not vulnerable and should be listed here..

Tim Smith
Product Manager - Chef Infra Server

**Comment by ad-m** [comment]
@tas50 could you provide a pull request and link to a public statement of Chef Infra?

**Comment by tas50** [comment]
https://github.com/NCSC-NL/log4shell/pull/120

**Comment by rkokkelk** [comment]
Fixed by  #120
