### ISSUE TITLE
script

### ISSUE THREAD

**Issue by janspook** [NCSC-NL/log4shell#172]
https://github.com/N-able/ScriptsAndAutomationPolicies/blob/master/Vulnerability%20-%20CVE-2021-44228%20(Log4j)/get-log4jrcevulnerability.ps1

this is a good script?

**Comment by pbeij** [comment]
Waiting till this is fixed: https://github.com/N-able/ScriptsAndAutomationPolicies/pull/28

**Comment by pbeij** [comment]
This issues in script are not fixed, I will close this issue.
If you have more information please let me know.
