### ISSUE TITLE
IGEL UMS vulnerable

### ISSUE THREAD

**Issue by martijngoorman** [NCSC-NL/log4shell#174]
IGEL UMS is vulnerable
Fix/Mitigation possible
A fixed version of UMS is in preparation
Source: https://kb.igel.com/securitysafety/en/isn-2021-11-ums-log4j-vulnerability-54086712.html

**Comment by maertsen** [comment]
hi @martijngoorman. Thanks for reaching out. Would you mind sending in a PR for this change? See https://docs.github.com/en/repositories/working-with-files/managing-files/editing-files if you are new to this.

**Comment by martijngoorman** [comment]
https://github.com/NCSC-NL/log4shell/pull/194

**Comment by maertsen** [comment]
thanks @martijngoorman
