### ISSUE TITLE
VMware Skyline Collector virtual appliance not vulnerable

### ISSUE THREAD

**Issue by DBVE** [NCSC-NL/log4shell#179]
https://kb.vmware.com/s/article/87068

**Comment by maertsen** [comment]
Thanks for reaching out. Would you mind sending in a PR for this change? See https://docs.github.com/en/repositories/working-with-files/managing-files/editing-files if you are new to this.

**Comment by Goldshop** [comment]
This Issue can be closed as PR is merged
