### ISSUE TITLE
CSV File

### ISSUE THREAD

**Issue by Appa-lw** [NCSC-NL/log4shell#190]
Hey, 
quick question:
Can you provide us with the software list as a CSV so that we can carry out a quick / automated comparison?

Parsing Markdown tables every update seems a bit much work...

Kind Regards
Appa

PS: Keep up the good work! ;)

**Comment by maertsen** [comment]
hi @Appa-lw, though we recognize the value, writing this script is currently not a priority for us. If you decide to write a script yourself, please consider opening a PR to share with the community.

**Comment by FF9680E59F9B** [comment]
You might want to check out #525. There is now a script to generate a CSV.
