### ISSUE TITLE
ISPNext not vulnerable 

### ISSUE THREAD

**Issue by DFFspace** [NCSC-NL/log4shell#229]
**Please file a PR instead of an issue** if you can. See https://docs.github.com/en/repositories/working-with-files/managing-files/editing-files#editing-files-in-another-users-repository. Thanks for your contribution!

Below a screenshot of their statement in the support portal which is behind a login
![image](https://user-images.githubusercontent.com/69241933/146024822-e21b2fa7-a1b8-430c-a73f-4d84c4660441.png)

**Comment by FF9680E59F9B** [comment]
As #250 is now merged this issue is resolved.
