### ISSUE TITLE
Please add eWON eCatcher 6.76

### ISSUE THREAD

**Issue by sammer003** [NCSC-NL/log4shell#269]
Please add vendor: eWON
software: eCatcher
version: 6.76
status: fixed
link: https://www.ewon.biz/technical-support/pages/all-downloads
document: https://hmsnetworks.blob.core.windows.net/www/docs/librariesprovider10/downloads-monitored/manuals/release-notes/ecatcher_releasenotes.txt?sfvrsn=4f054ad7_42

**Comment by FF9680E59F9B** [comment]
Thanks, added.
