### ISSUE TITLE
Fork 1lann

### ISSUE THREAD

**Issue by sebasmannem** [NCSC-NL/log4shell#313]
Ik heb de code van 1lann geforked en uitgebreid.
De fork staat (sinds gisteren avond) hier:
https://github.com/MannemSolutions/log4shelldetect/releases

Voordelen:

- Direct als binary gecompileerd
- Ook als container image beschikbaar
- hij scant ook .jar folders

**Comment by pbeij** [comment]
Waiting till it's more tested.

**Comment by pbeij** [comment]
I will close this issue for now, let me know if there is any news or updates on this fork.

**Comment by sebasmannem** [comment]
I have updated some on this fork. 
We now report on the lowest version included in the jar. And we scan wars as well. 
Please have another look if possible, and let me know if you have any questions.
