### ISSUE TITLE
Add Microsoft TFS / Azure DevOps

### ISSUE THREAD

**Issue by DoogeJ** [NCSC-NL/log4shell#33]
![image](https://user-images.githubusercontent.com/4255780/145793438-741e0732-b015-4cee-a197-8a66f509051f.png)

**Comment by maertsen** [comment]
Thanks @DoogeJ! We would very much appreciate a PR. Let me know if that causes issues (time or otherwise).

**Comment by PleunWillemsen** [comment]
https://jessehouwing.net/azure-devops-patch-for-log4j-vulnerability/
