### ISSUE TITLE
Dell Vulnerabilities

### ISSUE THREAD

**Issue by tintinhamans** [NCSC-NL/log4shell#34]
Dell has published a list of vulnerable products at the following page:

https://www.dell.com/support/kbdoc/nl-nl/printview/000194414/30/en

Hopefully this can be used to update the list of affected products.

**Comment by maertsen** [comment]
Thanks @tintinhamans! We would very much appreciate a PR. Let me know if that causes issues (time or otherwise).

**Comment by tintinhamans** [comment]
I'll get right on it 😃

**Comment by maertsen** [comment]
thanks!

**Comment by tintinhamans** [comment]
Forgot to add the software that is still under investigation, this should make the Dell list complete.
