### ISSUE TITLE
Please add Vuze A.K.A. Azureus

### ISSUE THREAD

**Issue by tobozo** [NCSC-NL/log4shell#365]
Hello,

I'm not sure if this software is eligible or how to test it, it holds a log4j.jar file and hasn't been updated for a while.

Vendor: https://www.vuze.com/
Software: Vuze (also know as Azureus)
Version: Revision 44261
Link: http://svn.vuze.com/public/client/trunk/uis/lib/
Status: unknown

Please let me know if this is worth a PR.

**Comment by maertsen** [comment]
yes, please submit a PR. Thanks for your time @tobozo!

**Comment by tobozo** [comment]
#476

**Comment by maertsen** [comment]
closing this in favor of the PR.
