### ISSUE TITLE
Sample DataSet to verify the regex | Regex is not working as tried on https://rubular.com/

### ISSUE THREAD

**Issue by ankit07070** [NCSC-NL/log4shell#393]
Hello,

The given regex is not working on variety of SIEM tools such as Splunk/SumoLogic.
I tried to test it on rubular.com but it seems the expression is malfunctioned.
Do you have a sample data to verify the claim?

**Comment by pbeij** [comment]
Edited the Regex to a new one.
Thanks for this information, if you have more please let me know.
