### ISSUE TITLE
Add Apache Tika 2.0 to the list

### ISSUE THREAD

**Issue by tacohiddink** [NCSC-NL/log4shell#40]
See https://tika.apache.org/2.0.0/index.html

**Comment by maertsen** [comment]
Thanks @tacohiddink! We would very much appreciate a PR. Let me know if that causes issues (time or otherwise).

**Comment by tacohiddink** [comment]
@maertsen mmh.. tried to push but got a permission/403 error for this repo
Can someone add:

`| Apache        | Tika | 2.0.0 and up | Vulnerable | |[source](https://tika.apache.org/2.0.0/index.html) |	`
