### ISSUE TITLE
Some of the products listed in the lists, is outdated or incorrect. What is needed to allow me to make the needed corrections?

### ISSUE THREAD

**Issue by rkeil-git** [NCSC-NL/log4shell#440]
Some of the products listed in the lists, is outdated or incorrect. What is needed to allow me to make the needed corrections?
I have the correct information for some of the products listed.

**Comment by maertsen** [comment]
hi @rkeil-git! Thanks for taking the time to review the list. We rely on contributions such as yours to make the most out of the list.

It's most helpful if you can submit pull requests with the corrections that you spot. We'll review and merge them. Thanks!
