### ISSUE TITLE
Do we add SaaS products?

### ISSUE THREAD

**Issue by martijnpolder** [NCSC-NL/log4shell#451]
As a customer of a SaaS product, you can't do much else than waiting. 
However, for assessing supply chain impact, adding SaaS providers can be helpful. 
OTOH, here are a million SaaS providers, adding these could make the software list untenable.

**Comment by maertsen** [comment]
Feel free to submit PR's for SaaS-vendors you rely on, @martijnpolder. The current software scope is potentially untenable as it is, but it provides value to people anyway. So don't hold yourself back :-)
