### ISSUE TITLE
VMware products that are not vulnerable

### ISSUE THREAD

**Issue by DBVE** [NCSC-NL/log4shell#48]
https://kb.vmware.com/s/article/87068?lang=en_US

**Comment by maertsen** [comment]
Thanks @DBVE! We would very much appreciate a PR. Let me know if that causes issues (time or otherwise).

**Comment by DBVE** [comment]
If i want to make a PR than i get the following message:
Choose different branches or forks above to discuss and review changes. Learn about pull requests

**Comment by maertsen** [comment]
No worries @DBVE, I'll have a go. Thanks for bringing this to our attention.

**Comment by maertsen** [comment]
@DBVE a number of VMware products were added. Can you check if you are missing anything relevant to you?

**Comment by DBVE** [comment]
@maertsen missing vcloud director and workstation. After these two entry's are added this issue can be closed.

**Comment by DBVE** [comment]
@maertsen fyi the FQ~~D~~N of both products are
VMware Cloud Director
VMware Workstation
