### ISSUE TITLE
Regex Compatibility with ECMA Script(Java Script)

### ISSUE THREAD

**Issue by VivekMohanP** [NCSC-NL/log4shell#52]
Hi Team,
we wanted incorporate this regex in javascript based solution, could  you please help with ECMA Script flavor of detection regex expression

**Comment by bolshoytoster** [comment]
Are you talking about [this](https://github.com/NCSC-NL/log4shell/tree/main/mitigation#overall-detection-regex)?

If so, I channelled the voodoo magic of regex and made this:
```javascript
\${jndi:(ldap[s]?|rmi|dns):\/\/.*?}[^{]*?}
```
It works with one layer of nested brackets, that should be enough for this.

**Comment by pbeij** [comment]
Edited the Regex to a new one.
Thanks for this information, if you have more please let me know.
