### ISSUE TITLE
Idea: create an csv file of software

### ISSUE THREAD

**Issue by sevickson** [NCSC-NL/log4shell#525]
To be able to use the information in https://github.com/NCSC-NL/log4shell/tree/main/software to check against lists of installed software.
This would make it easy to use the list to check offline for installed software.
Maybe an automated process to create the list when it is updated through the PR process.

**Comment by maertsen** [comment]
hi @sevickson, these can now be found at https://github.com/NCSC-NL/log4shell/releases.
