### ISSUE TITLE
Software list stops at " Riverbed" 

### ISSUE THREAD

**Issue by IshangoNL** [NCSC-NL/log4shell#658]
When viewing the list of software items. Riverbed is the last entry that is visible. Letters S through Z don't respond either. Buffer issue?

**Comment by Fxr12042** [comment]
The displayed readme.md in the main repo is limited. See also https://github.community/t/does-readme-md-have-max-characters/128124/7
Limit seems to be 512kb? You need to specificially open the readme.md to see the full list.
