### ISSUE TITLE
What do you think about this regex

### ISSUE THREAD

**Issue by ifle** [NCSC-NL/log4shell#669]
```
(?:\${)?(?:j|.+?[$:-]j)(?:n|.+?[$:-]n)(?:d|.+?[$:-]d)(?:i|.+?[$:-]i)
```

**Comment by ChrisForsythe** [comment]
Take a look here. https://github.com/back2root/log4shell-rex

**Comment by pbeij** [comment]
Edited the Regex to a new one.
Thanks for this information, if you have more please let me know.
