### ISSUE TITLE
Somewhere between #648 and $current, all listings >R have disappeared

### ISSUE THREAD

**Issue by utvikler** [NCSC-NL/log4shell#670]
FYI, as of version > #649 the software list is missing everything from R-Z.  FYI.  Thanks for the great effort!

**Comment by DFFspace** [comment]
I noticed this to, but when you open the readme file https://github.com/NCSC-NL/log4shell/blob/main/software/README.md it shows all content maybe it has something to do with github that it has a limit when not viewing the file itself?

**Comment by utvikler** [comment]
> I noticed this to, but when you open the readme file https://github.com/NCSC-NL/log4shell/blob/main/software/README.md it shows all content maybe it has something to do with github that it has a limit when not viewing the file itself?

Thank you, thats a workaround, at least.  Consider perhaps a little direct link at the top of the default page?

**Comment by utvikler** [comment]
Closing, anyhow.  This does appear to be a limitation in github...
