### ISSUE TITLE
Quadiant Hybridmail en Automation

### ISSUE THREAD

**Issue by sebastiaanbobbink** [NCSC-NL/log4shell#680]
Geen officieel statement op de website, wel communicatie per mail.
Hybridmail kan kwetsbaar zijn afhankelijk van de versie, Automation is kwetsbaar.

The Hybridmail back end - Inspire Automation may be affected depending on used version.
Inspire Automation 11.2 and higher is affected by the recently found vulnerability.
Older Automation releases like 10.0, 11.0 are using previous release of Log4J library which is not affected by the vulnerability.

To mitigate the vulnerability in affected Automation version it's possible to follow steps in this article:
https://university.quadient.com/c/portal/kb/find_article?resourcePrimKey=36912100

There will be hotfixes released with new Log4j library containing fix of the issue in Inspire Automation 12.0.77.0, 14.0.69.0, 15.0.418.0, 15.2.413.0, 15.3.404.0.

**Comment by maertsen** [comment]
@sebastiaanbobbink would you mind submitting a PR with this information? You can include a screenshot of your e-mail, redacted to exclude personal data. See https://docs.github.com/en/repositories/working-with-files/managing-files/editing-files#editing-files-in-another-users-repository if this is new for you. Thanks!

**Comment by maertsen** [comment]
Closing due to lack of reponse. PR's to add this information are still more than welcome @sebastiaanbobbink.
