### ISSUE TITLE
Affected Software main page is broken at Lenovo

### ISSUE THREAD

**Issue by ppaulie** [NCSC-NL/log4shell#741]
**Please file a PR instead of an issue** if you can. See https://docs.github.com/en/repositories/working-with-files/managing-files/editing-files#editing-files-in-another-users-repository. Thanks for your contribution!

Hi someone tried to add a link to a Lenovo source and broke the Software main page.

https://github.com/NCSC-NL/log4shell/tree/main/software#l

**Comment by pbeij** [comment]
Hi Ppaulie, thanks for reporting this issue.
On the software page the first lines acknowledge this issue, there is a alternative link which shows all the reported software.

Important: GitHub only shows the first 512kb of this file in the preview. If you don't see the entire software list, please click here (https://github.com/NCSC-NL/log4shell/blob/main/software/README.md) to load the entire list.

If you have any more issues or recommendations please let me know!
