### ISSUE TITLE
mitel phone systems

### ISSUE THREAD

**Issue by mosscomm** [NCSC-NL/log4shell#773]
**Please file a PR instead of an issue** if you can. See https://docs.github.com/en/repositories/working-with-files/managing-files/editing-files#editing-files-in-another-users-repository. Thanks for your contribution!

https://www.mitel.com/support/security-advisories/mitel-product-security-advisory-21-0010

**Comment by maertsen** [comment]
Mitel has 21 entries in the software list by now. Any updates welcome @mosscomm.
