### ISSUE TITLE
Version vs Status

### ISSUE THREAD

**Issue by tschmidtb51** [NCSC-NL/log4shell#95]
There seems to be some misleading information when combining version and status field, e.g.

| Supplier        | Product         | Version         | Status          | Notes           | Links |
|:----------------|:----------------|:---------------:|:---------------:|:----------------|-----------:|
| Apache        | Log4j | < 2.15.0 | Fix | |[source](https://logging.apache.org/log4j/2.x/security.html) |

That could be interpreted at any log4j < 2.15.0 if fixed which is wrong...

**Comment by tintinhamans** [comment]
Perhaps renaming the version column to "Affected Version" would help to mitigate this.

**Comment by OmgImAlexis** [comment]
@tschmidtb51 yep that's how I was reading..

**Comment by maertsen** [comment]
Good morning, thanks for bringing this up. We've just discussed this within NCSC-NL and decided as follows:

The version number should relate to the status in the status column.

In other words: if status is vulnerable, the version number indicates vulnerable versions. If status is fix, the version indicates the first fixed version.

We'll clarify this in the document shortly. Please open PRs when you discover that a versionnumber is incorrect under this clarified interpretation. With a list this big, there's bound to be some mistakes, but I'm confident we can do this together.
