### ISSUE TITLE
SonarQube not vulnerable

### ISSUE THREAD

**Issue by jeroenvanroon** [NCSC-NL/log4shell#96]
I like to report that SonarQube is not vulnerable at the moment. It can be helpful if this is added to the list.

For more information: https://community.sonarsource.com/t/sonarqube-sonarcloud-and-the-log4j-vulnerability/54721

**Comment by delgurth** [comment]
Actually. SonarQube says:

> SonarQube includes a component from ElasticSearch that contains a Log4J component. At this time, we cannot affirm that there is no risk from this component. We recommend that you add the following property in sonar.properties or through an environment variable and then restart your SonarQube instance. This will effectively mitigate any risk there might be:
> 
> sonar.search.javaAdditionalOpts=-Dlog4j2.formatMsgNoLookups=true

So not sure if it's affected or not. The ElasticSearch part contains log4j-core, so it has the potential of being vulnerable.

**Comment by FF9680E59F9B** [comment]
It's not completely clear to me if SonarQube is vulnerable or not. The fact that SonarSource has published a mitigation is enough reason for me to retain the status "Workaround". If you think this is not the right choice please let us know in this issue.
